### ISSUE TITLE
reference ask

### ISSUE THREAD

**Issue by impce-lg** [utiasSTARS/msckf-swf-comparison#3]
Dear author，does this code refer someone's PhD thesis，and would u send me one？
Looking forward your reply！
many thanks and best wishes to u！

**Comment by impce-lg** [comment]
My email address：773792173@qq.com
thx

**Comment by moshanATucsd** [comment]
refer to [paper](http://www.starslab.ca/wp-content/papercite-data/pdf/2015_clement_battle.pdf)
